import chainlit as cl
from langchain_core.messages import HumanMessage, AIMessage
from core.graph import graph, coordinator
from core.database import initialize_database
from core.config import DB_PATH, ROOT_DIR, DB_URL
import os
import secrets
from chainlit.data.sql_alchemy import SQLAlchemyDataLayer

# --- Local-First Persistence & Transparency Setup ---

def ensure_auth_secret():
    """Ensures a CHAINLIT_AUTH_SECRET exists and is persisted in .env."""
    env_path = ROOT_DIR / ".env"
    secret = os.environ.get("CHAINLIT_AUTH_SECRET")
    
    if not secret:
        # Check if it's in the .env file but not in environment
        if env_path.exists():
            with open(env_path, "r") as f:
                for line in f:
                    if line.startswith("CHAINLIT_AUTH_SECRET="):
                        secret = line.split("=")[1].strip()
                        os.environ["CHAINLIT_AUTH_SECRET"] = secret
                        break
        
        if not secret:
            secret = secrets.token_hex(32)
            os.environ["CHAINLIT_AUTH_SECRET"] = secret
            # Persist to .env
            mode = "a" if env_path.exists() else "w"
            with open(env_path, mode) as f:
                f.write(f"\n# Generated by IslamAI for local auth features\nCHAINLIT_AUTH_SECRET={secret}\n")
    return secret

# 1. Initialize Secrets
ensure_auth_secret()

# 2. Database Connection & Initialization
# Automated schema check/initialization on every startup
initialize_database(str(DB_PATH))

@cl.data_layer
def get_data_layer():
    return SQLAlchemyDataLayer(conninfo=DB_URL)

# 3. Transparent Authentication
# We return a fixed user object to bypass the login UI while enabling history features.
@cl.header_auth_callback
def header_auth_callback(headers: dict):
    return cl.User(identifier="local-user", metadata={"role": "admin"})

@cl.on_chat_resume
async def on_chat_resume(thread: dict):
    """Restores the LangGraph message history when a chat is resumed from the sidebar."""
    messages = []
    for step in thread.get("steps", []):
        if step.get("type") == "user_message":
            messages.append(HumanMessage(content=step.get("output")))
        elif step.get("type") == "assistant_message":
            messages.append(AIMessage(content=step.get("output")))
    
    cl.user_session.set("messages", messages)

# ---------------------------------------------------


@cl.set_starters
async def set_starters():
    return [
        cl.Starter(
            label="Sahabi with doubled testimony & Quran compilation",
            message="Which Companion of the Prophet ﷺ had his testimony counted as equal to two witnesses, and how did this unique distinction later play a role during the compilation of the Qur'an?",
            icon="/public/quran_icon.svg",
        ),
    ]


@cl.on_chat_start
async def start():
    """Initializes the chat session and syncs the knowledge base."""
    cl.user_session.set("messages", [])

    if coordinator:
        async with cl.Step(name="System Initialization") as step:
            step.output = "Syncing Islamic knowledge base (Quran & Hadith)..."
            # Run sync in a thread to avoid blocking the event loop
            await cl.make_async(coordinator.sync_documents)()
            
            # Eagerly load the embedding model to prevent lag on first search
            step.output = "Optimizing search performance (loading model)..."
            await cl.make_async(coordinator.embedding_manager.load_embedding_model)()
            
            step.output = "Knowledge base is up to date and ready."


@cl.on_message
async def main(message: cl.Message):
    """Handles incoming messages by streaming the LangGraph response."""
    messages = cl.user_session.get("messages")
    messages.append(HumanMessage(content=message.content))

    # Streaming response placeholder (we will send it only when LLM starts the final answer)
    response_msg: cl.Message | None = None
    tool_steps: dict[str, cl.Step] = {}
    final_answer = ""

    async for event in graph.astream_events(
        {"messages": messages},
        version="v2",
    ):
        kind = event["event"]
        name = event.get("name", "")

        if kind == "on_chat_model_stream":
            chunk = event["data"].get("chunk")
            if chunk and chunk.content:
                # If this is the first token of the final answer, send the message container
                if response_msg is None:
                    response_msg = cl.Message(content="")
                    await response_msg.send()

                if isinstance(chunk.content, str):
                    await response_msg.stream_token(chunk.content)
                    final_answer += chunk.content
                elif isinstance(chunk.content, list):
                    for part in chunk.content:
                        if isinstance(part, dict) and part.get("type") == "text":
                            text = part["text"]
                            await response_msg.stream_token(text)
                            final_answer += text

        # Tool handling (improved step names and placement)
        elif kind == "on_tool_start":
            tool_input = event["data"].get("input", {})
            # Cleaner formatting for tool names
            friendly_name = name.replace("search_", "Searching ").replace("_", " ").title()
            
            step = cl.Step(name=friendly_name, type="tool")
            await step.__aenter__()
            step.input = str(tool_input)
            tool_steps[event["run_id"]] = step

        elif kind == "on_tool_end":
            run_id = event["run_id"]
            if run_id in tool_steps:
                step = tool_steps.pop(run_id)
                output = event["data"].get("output", "")
                step.output = f"Retrieved relevant data from the {name.split('_')[-1]}."
                await step.__aexit__(None, None, None)

    # Finalize the streaming message if it was ever created
    if response_msg:
        await response_msg.update()

    # Update session history with the AI response
    messages.append(AIMessage(content=final_answer))
    cl.user_session.set("messages", messages)